
DECLARE @STARTDATE      DATE;
DECLARE @ENDDATE        DATE;
SET @STARTDATE =  '2017-01-01';   
SELECT  @ENDDATE =DATEADD(MONTH,23,@STARTDATE );

WITH DATES_CTE([DATE])   
AS
(
   SELECT @STARTDATE AS [DATE]
   UNION ALL
   SELECT DATEADD(MONTH,1, [DATE] )
   FROM DATES_CTE 
   WHERE [DATE] < @ENDDATE	
)

select * from DATES_CTE
--OPTION (MAXRECURSION 0)  -- default max recursive er 100 , ca 8år..